version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1523532572
layout:
  /header/:
    -
      - 'logo-6601 30'
      - 'spacer-5221 70'
  /main/:
    -
      - system-messages-5119
    -
      - system-content-4750
  /footer/:
    -
      - position-footer
    -
      - 'copyright-2065 40'
      - 'spacer-9459 30'
      - 'branding-9219 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
