<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Create a shortcut for params.
$params = $this->item->params;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_prods_associations'));
?>
<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
	|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate())) : ?>
	<div class="system-unpublished">
<?php endif; ?>

<?php if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
	<?php echo JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
<?php endif; ?>

<?php // Todo Not that elegant would be nice to group the params ?>
<?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
	|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
  <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
	<?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php if ($info == 0 && $params->get('show_prods_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php echo JLayoutHelper::render('joomla.content.prods_tags', $this->item->tags->itemTags); ?>
	<?php endif; ?>
<?php endif; ?>

<?php // картинка, изображение, intro_image img ?>
<?php // echo JLayoutHelper::render('joomla.content.prods_intro_image', $this->item); ?>

<?php if (!$params->get('show_intro')) : ?>
	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?=$this->item->event->afterDisplayTitle; ?>
<?php endif; ?>

<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
<?=$this->item->event->beforeDisplayContent; ?>
<?php // текст ?>
<?php //echo $this->item->introtext; ?>

<?php // start поля ?>
<?php $myCustomFields = array();
	foreach($this->item->jcfields as $field) :
		$myCustomFields[$field->name] = $field->value;
	endforeach; ?>
		<tbody>
			<tr>
				<?='<td data-label="' . JText::_('NAME'). '">' . JLayoutHelper::render('joomla.content.prods_style_default_item_title', $this->item) . '</td>'; ?>
				<?php if (isset($myCustomFields['purpose']) and !empty($myCustomFields['purpose'])) : ?>
				<?='<td data-label="' . JText::_('PURPOSE') . '">' . $myCustomFields['purpose'] . '</td>';endif;?>
				<?php if (isset($myCustomFields['size']) and !empty($myCustomFields['size'])) : ?>
					<?='<td data-label="' . JText::_('SIZE') . '">' . $myCustomFields['size'] . '</td>'; endif; ?>
				<?php if (isset($myCustomFields['capacity']) and !empty($myCustomFields['capacity'])) : ?>
					<?='<td data-label="' . JText::_('CAPACITY') . '">' . $myCustomFields['capacity'] . '</td>'; endif; ?>
				<?php if (isset($myCustomFields['current']) and !empty($myCustomFields['current'])) : ?>
					<?='<td data-label="' . JText::_('CURRENT') . '">' . $myCustomFields['current'] . '</td>'; endif; ?>
				<?php if (isset($myCustomFields['polarity']) and !empty($myCustomFields['polarity'])) : ?>
					<?='<td data-label="' . JText::_('POLARITY') . '">' . $myCustomFields['polarity'] . '</td>'; endif; ?>
				<?php if (isset($myCustomFields['quantity']) and !empty($myCustomFields['quantity'])) : ?>
					<?='<td data-label="' . JText::_('QUANTITY') . '">' . $myCustomFields['quantity'] . '</td>'; endif; ?>
				<?php if (isset($myCustomFields['weight']) and !empty($myCustomFields['weight'])) : ?>
					<?='<td data-label="' . JText::_('WEIGHT') . '">' . $myCustomFields['weight'] . '</td>'; endif; ?>
				<?php if (isset($myCustomFields['download']) and !empty($myCustomFields['download'])) : ?>
					<?='<td data-label="' . JText::_('DOCUMENTATION'). '">' . $myCustomFields['download'] . '</td>'; endif; ?>
			</tr>
		</tbody>
<?php // finish поля ?>
<?php if ($useDefList && ($info == 1 || $info == 2)) : ?>
	<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
	<?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
	<?php if ($params->get('show_prods_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php echo JLayoutHelper::render('joomla.content.prods_tags', $this->item->tags->itemTags); ?>
	<?php endif; ?>
<?php endif; ?>

<?php if ($params->get('show_readmore') && $this->item->readmore) :
	if ($params->get('access-view')) :
		$link = JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language));
	else :
		$menu = JFactory::getApplication()->getMenu();
		$active = $menu->getActive();
		$itemId = $active->id;
		$link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
		$link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
	endif; ?>

	<?php echo JLayoutHelper::render('joomla.content.prods_readmore', array('item' => $this->item, 'params' => $params, 'link' => $link)); ?>

<?php endif; ?>

<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
	|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate())) : ?>
</div>
<?php endif; ?>

<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
<?=$this->item->event->afterDisplayContent; ?>
