name: _body_only
timestamp: 1523532572
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1523532572
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-3296: 'System Messages'
  content:
    system-content-2692: 'Page Content'
inherit: {  }
